### ISSUE TITLE
"Get a temporary place name" button doesn't work properly

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/Iamus#24]
Clean install of server on Windows.
In server start-up wizard, skip step 2 (to do with getting a place name).
In server settings table there is no temporary place name listed.
Press the "Get a temporary place name" button.
There is still no temporary place name listed.

![cant-create-temp-placename](https://user-images.githubusercontent.com/7455448/94213842-14c01d00-ff2c-11ea-9ee6-af5a49fa102a.png)

Version: Vircadia-Alpha-PR668-c4e4b61_9e8dc88f.exe

Looking in https://dashboard.vircadia.com/places it would appear that two temporary place names were created during the above: the first probably during the wizard and the second after clicking the button.

**Comment by kasenvr** [comment]
Pretty sure I fixed this with this... https://github.com/kasenvr/project-athena/pull/668/commits/9e8dc88f63060cc224d9cc7f75c394dfade774b1 but I will be able to confirm that loop once I can navigate to places in Interface.

**Comment by ctrlaltdavid** [comment]
The Installer version I'm using includes that commit, so looks like not fixed.

**Comment by kasenvr** [comment]
Oh, place name listed, I see what you mean.

**Comment by Misterblue** [comment]
The problem was that the correct fields were not begin returned so the settings web page didn't display the name that had been generated.
There might still be some hiccups with the handoff between the settings web page and the dashboard, but this particular problem is fixed in 2.2.7.
